In [1]:
import numpy as np
import pandas as pd

In [2]:
df_imdb = pd.read_csv("simpsons_imdb.csv", sep=",", index_col=0)
df_imdb["airdates"] = df_imdb["airdates"].replace("22 Dec. 1990", "17 Dec. 1989")
df_imdb

,title,summaries,airdates,rankings,total_votes,links
0,Simpsons Roasting on an Open Fire,Homer is forced to become a department store S...,17 Dec. 1989,8.1,7529,https://www.imdb.com/title/tt0348034/
1,Bart the Genius,Bart ends up at a school for gifted children a...,14 Jan. 1990,7.7,5015,https://www.imdb.com/title/tt0756593/
2,Homer's Odyssey,"After losing his job, Homer contemplates endin...",21 Jan. 1990,7.3,4427,https://www.imdb.com/title/tt0701124/
3,There's No Disgrace Like Home,After being embarrassed by the rest of the fam...,28 Jan. 1990,7.7,4353,https://www.imdb.com/title/tt0756399/
4,Bart the General,After being beaten up by Nelson Muntz one too ...,4 Feb. 1990,7.9,4687,https://www.imdb.com/title/tt0701059/
...,...,...,...,...,...,...
722,My Octopus and a Teacher,Bart has romantic feelings for his new teacher...,24 Apr. 2022,6.6,348,https://www.imdb.com/title/tt14458056/
723,Girls Just Shauna Have Fun,Lisa finds an unlikely mentor in Shauna Chalme...,1 May 2022,6.6,325,https://www.imdb.com/title/tt14458070/
724,Marge the Meanie,Marge bonds with Bart when she discovers a sec...,8 May 2022,6.7,301,https://www.imdb.com/title/tt14458078/
725,Meat Is Murder,Grampa reconnects with an old associate in the...,15 May 2022,5.8,335,https://www.imdb.com/title/tt14458098/
726,Poorhouse Rock,"Bart finally learns to admire Homer, but a vis...",22 May 2022,5.6,515,https://www.imdb.com/title/tt14458122/

In [3]:
df_imdb["date_imdb"] = df_imdb.airdates.str.replace(' Jan. ', '/01/', regex=True).replace(' Feb. ', '/02/', regex=True).replace(' Mar. ', '/03/', regex=True).replace(' Apr. ', '/04/', regex=True).replace(' May ', '/05/', regex=True).replace(' Jun. ', '/06/', regex=True).replace(' Jul. ', '/07/', regex=True).replace(' Aug. ', '/08/', regex=True).replace(' Sep. ', '/09/', regex=True).replace(' Oct. ', '/10/', regex=True).replace(' Nov. ', '/11/', regex=True).replace(' Dec. ', '/12/', regex=True)
df_imdb.date_imdb = pd.to_datetime(df_imdb.date_imdb,format='%d/%m/%Y',errors='coerce')
df_imdb

,title,summaries,airdates,rankings,total_votes,links,date_imdb
0,Simpsons Roasting on an Open Fire,Homer is forced to become a department store S...,17 Dec. 1989,8.1,7529,https://www.imdb.com/title/tt0348034/,1989-12-17
1,Bart the Genius,Bart ends up at a school for gifted children a...,14 Jan. 1990,7.7,5015,https://www.imdb.com/title/tt0756593/,1990-01-14
2,Homer's Odyssey,"After losing his job, Homer contemplates endin...",21 Jan. 1990,7.3,4427,https://www.imdb.com/title/tt0701124/,1990-01-21
3,There's No Disgrace Like Home,After being embarrassed by the rest of the fam...,28 Jan. 1990,7.7,4353,https://www.imdb.com/title/tt0756399/,1990-01-28
4,Bart the General,After being beaten up by Nelson Muntz one too ...,4 Feb. 1990,7.9,4687,https://www.imdb.com/title/tt0701059/,1990-02-04
...,...,...,...,...,...,...,...
722,My Octopus and a Teacher,Bart has romantic feelings for his new teacher...,24 Apr. 2022,6.6,348,https://www.imdb.com/title/tt14458056/,2022-04-24
723,Girls Just Shauna Have Fun,Lisa finds an unlikely mentor in Shauna Chalme...,1 May 2022,6.6,325,https://www.imdb.com/title/tt14458070/,2022-05-01
724,Marge the Meanie,Marge bonds with Bart when she discovers a sec...,8 May 2022,6.7,301,https://www.imdb.com/title/tt14458078/,2022-05-08
725,Meat Is Murder,Grampa reconnects with an old associate in the...,15 May 2022,5.8,335,https://www.imdb.com/title/tt14458098/,2022-05-15
726,Poorhouse Rock,"Bart finally learns to admire Homer, but a vis...",22 May 2022,5.6,515,https://www.imdb.com/title/tt14458122/,2022-05-22

In [4]:
df_episodes = pd.read_csv("simpsons_episodes.csv", sep=",")
df_episodes = df_episodes.drop(columns=["image_url", "production_code", "video_url"])
df_episodes['date_kaggle'] = pd.to_datetime(df_episodes.original_air_date,infer_datetime_format=True,errors='coerce')
df_episodes

,id,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,season,title,us_viewers_in_millions,views,date_kaggle
0,10,7.4,1511.0,10,10,1990-03-25,1990,1,Homer's Night Out,30.30,50816.0,1990-03-25
1,12,8.3,1716.0,12,12,1990-04-29,1990,1,Krusty Gets Busted,30.40,62561.0,1990-04-29
2,14,8.2,1638.0,1,14,1990-10-11,1990,2,"Bart Gets an ""F""",33.60,59575.0,1990-10-11
3,17,8.1,1457.0,4,17,1990-11-01,1990,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,64959.0,1990-11-01
4,19,8.0,1366.0,6,19,1990-11-15,1990,2,Dead Putting Society,25.40,50691.0,1990-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,7.0,580.0,14,500,2012-02-19,2012,23,At Long Last Leave,5.77,45226.0,2012-02-19
596,502,7.3,541.0,16,502,2012-03-11,2012,23,How I Wet Your Mother,4.97,44818.0,2012-03-11
597,511,6.9,460.0,3,511,2012-11-04,2012,24,Adventures in Baby-Getting,5.65,39687.0,2012-11-04
598,542,6.4,473.0,12,542,2014-03-09,2014,25,Diggs,2.69,39292.0,2014-03-09
599,548,7.0,504.0,18,548,2014-04-13,2014,25,Days of Future Future,3.64,55742.0,2014-04-13

In [5]:
#df_imdb["title_merge"] = df_imdb["title"].str.lower().str.replace(r'[^\w\s]+', '').str.replace(' ', '')
#df_episodes["title_merge"] = df_episodes["title"].str.lower().str.replace(r'[^\w\s]+', '').str.replace(' ', '')
#df_episodes = df_episodes.replace({'title_merge':{'aloneagainnaturadiddily': 'aloneagainnaturadiddly', 'amidsummersnicedream': 'amidsummersnicedreams', 'atotallyfunthingthatbartwillneverdoagain': 'atotallyfunthingbartwillneverdoagain', 'bartvslisavsthethirdgrade': 'bartvslisavs3rdgrade', 'byebyenerdie': 'byebyenerdy', 'elviajemisteriosodenuestrojomerthemysteriousvoyageofhomer': 'elviajemisteriosodenuestrojomer', 'friendsandfamily203': 'friendsandfamily', 'homesweethomediddlydumdoodily': 'homesweethomedumdiddlydoodily', 'homervstheeighteenthamendment': 'homervsthe18thamendment', 'jazzyandthepussycats': 'jazzythepussycats', 'killgilvolumesiii': 'killgilvol12', 'margeandhomerturnacoupleplay': 'homerandmargeturnacoupleplay', 'nednednasblend': 'nednednasblendagenda', 'obrotherwherebartthou': 'ohbrotherwhereartthou', 'poppasgotabrandnewbadge': 'papasgotabrandnewbadge', 'summerof4ft2': 'summerof42', 'thechangingoftheguardian': 'changingoftheguardian', 'thehomerofseville': 'homerofseville', 'thetown205': 'thetown', 'treehouseofhorrorxxvii207': 'treehouseofhorrorxxvii'}})
#df = df_imdb.merge(df_episodes, on='date_merge', how='outer')

In [6]:
df_imdb.to_csv(r'/Users/heloisevanrenterghem/Documents/THPprojets/imdb_cleaned.csv')

In [7]:
df_episodes.to_csv(r'/Users/heloisevanrenterghem/Documents/THPprojets/episodes_cleaned.csv')